services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  YourVendor\InvoiceIQBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'
